openapi: 3.0.3
info:
  title: "Cloud Image Directory"
  description: |-
    This is an experimental project and a work in progress with the goal of making it easier to find Red Hat Enterprise Linuxâ„¢, Fedora and, in the future, a bunch of other linux images at various public cloud providers. You can find more information about it at [https://github.com/redhatcloudx/cloud-image-directory](https://github.com/redhatcloudx/cloud-image-directory)
  version: 0.0.1

servers:
  - url: https://imagedirectory.cloud/

components:
  schemas:
    V1_Page_Details_Provider_Request:
      properties:
        provider:
          type: string
      example:
        provider: "aws"

    V1_Page_Details_Response:
      properties:
        first:
          type: integer
        last:
          type: integer
        entries:
          type: integer
      example:
        first: 0
        last: 224
        entries: 50

    V1_List_Latest_Images_Provider_Request:
      properties:
        provider:
          type: string
        page:
          type: integer
      example:
        provider: "aws"
        page: 1

    V1_List_Latest_Images_Provider_Response:
      properties:
        name:
          type: string
        date:
          type: string
        provider:
          type: string
        ref:
          type: string
        arch:
          type: string
        region:
          type: string
      example:
        name: "RHEL 8.1.0 hvm arm64 Hourly2"
        date: "2023-05-15"
        provider: "aws"
        ref: "aws/ap-south-2/rhel_8.1.0_hvm_arm64_hourly2"
        arch: "arm64"
        region: "ap-south-2"

    V1_Latest_Images_Response:
      properties:
        name:
          type: string
        date:
          type: string
        provider:
          type: string
        ref:
          type: string
        arch:
          type: string
        region:
          type: string
      example:
        name: "RHEL 8.1.0 hvm arm64 Hourly2"
        date: "2023-05-15"
        provider: "aws"
        ref: "aws/ap-south-2/rhel_8.1.0_hvm_arm64_hourly2"
        arch: "arm64"
        region: "ap-south-2"

    V1_Image_Names_Response:
      properties:
        name:
          type: string
      example:
        ["aws/af-south-1/rhel_7.9_hvm_x86_64_hourly2",
          "azure/australiaeast/osa_osa_311_x64",
          "google/global/rhel_7_x86_64"]

    V1_Image_Details_Request:
      properties:
        provider:
          type: string
        region:
          type: string
        image-name:
          type: string
      example:
        provider: "aws"
        region: "af-south-1"
        image-name: "rhel_7.9_ha_hvm_x86_64_hourly2"

    V1_Image_Details_Response:
      properties:
        name:
          type: string
        arch:
          type: string
        version:
          type: string
        imageId:
          type: string
        date:
          type: string
        virt:
          type: string
        selflink:
          type: string
        region:
          type: string
      example:
        name: "RHEL 7.9 HA hvm x86_64 Hourly2"
        arch: "x86_64"
        version: "7.9"
        imageId: "ami-0fb78bc7f205f25fb"
        date: "2022-10-27T21:19:34.000Z"
        virt: "hvm"
        selflink: "https://console.aws.amazon.com/ec2/home?region=af-south-1#launchAmi=ami-0fb78bc7f205f25fb"
        region: "af-south-1"

    V2_OS_Response:
      properties:
        name:
          type: string
        display_name:
          type: string
        description:
          type: string
        count:
          type: integer
      example:
        {
          "name": "rhel",
          "display_name": "Red Hat Enterprise Linux",
          "description": "Red Hat Enterprise Linux",
          "count": 207
        }

    V2_Provider_Request:
      properties:
        os:
          type: string
      example:
        os: "rhel"

    V2_Provider_Response:
      properties:
        aws:
          type: integer
        azure:
          type: integer
        google:
          type: integer
      example:
        aws: 43
        azure: 153
        google: 11

    V2_Version_Request:
      properties:
        os:
          type: string
        provider:
          type: string
      example:
        os: "rhel"
        provider: "aws"

    V2_Version_Response:
      properties:
        8.5:
          type: integer
        8.5.0:
          type: integer
        8.6.0:
          type: integer
        7.9:
          type: integer
        8.1.0:
          type: integer
        6.10:
          type: integer
        8.2.0:
          type: integer
        9.0.0:
          type: integer
        8.7.0:
          type: integer
        9.1.0:
          type: integer
        8.4.0:
          type: integer
      example:
        {
          "8.5": 3,
          "8.5.0": 6,
          "8.6.0": 5,
          "7.9": 2,
          "8.1.0": 3,
          "6.10": 1,
          "8.2.0": 4,
          "9.0.0": 6,
          "8.7.0": 5,
          "9.1.0": 5,
          "8.4.0": 3
        }

    V2_Region_Request:
      properties:
        os:
          type: string
        provider:
          type: string
        version:
          type: string
      example:
        os: "rhel"
        provider: "aws"
        version: "9.0.0"

    V2_Region_Response:
      properties:
        eu-west-1:
          type: integer
        me-central-1:
          type: integer
        me-south-1:
          type: integer
      example:
        eu-west-1: 1
        me-central-1: 2
        me-south-1: 3

    V2_Image_Request:
      properties:
        os:
          type: string
        provider:
          type: string
        version:
          type: string
        region:
          type: string
      example:
        os: "rhel"
        provider: "aws"
        version: "9.0.0"
        region: "eu-west-1"

    V2_Image_Response:
      example:
        c605525f1072296fd6679ff0a7ca6003812e4815

    V2_All_Response:
      properties:
        name:
          type: string
        arch:
          type: string
        version:
          type: string
        imageId:
          type: string
        date:
          type: string
        selflink:
          type: string
        provider:
          type: string
        region:
          type: string
      example:
        name: "RHEL 7.9 sap X86_64"
        arch: "X86_64"
        version: "7.9"
        imageId: "https://www.googleapis.com/compute/v1/projects/rhel-sap-cloud/global/images/rhel-7-9-sap-v20230306"
        date: "2023-03-06T12:57:17.667-08:00"
        selflink: "https://console.cloud.google.com/compute/imagesDetail/projects/rhel-sap-cloud/global/images/rhel-7-9-sap-v20230306"
        provider: "google"
        region: "global"


paths:
  /images/v1/idx/list/sort-by-date/pages:
    get:
      summary: List page details
      description: ""
      tags:
        - "V1 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_Page_Details_Response"
        "5XX":
          description: "Unexpected error."

  /images/v1/idx/list/sort-by-date/{page}:
    get:
      summary: List latest images
      description: ""
      parameters:
        - in: path
          required: true
          name: page
          schema:
            type: string
      tags:
        - "V1 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_Latest_Images_Response"
        "404":
          description: "The given page does not exist."
        "5XX":
          description: "Unexpected error."

  /images/v1/idx/list/sort-by-date-{provider}/pages:
    get:
      summary: List page details sorted by provider
      description: ""
      parameters:
      - in: path
        required: true
        name: provider
        schema:
          type: string
      tags:
        - "V1 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_Page_Details_Response"
        "5XX":
          description: "Unexpected error."

  /images/v1/idx/list/sort-by-date-{provider}/{page}:
    get:
      summary: List latest images sorted by provider
      description: ""
      parameters:
      - in: path
        required: true
        name: provider
        schema:
          type: string
      - in: path
        required: true
        name: page
        schema:
          type: string
      tags:
        - "V1 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_List_Latest_Images_Provider_Response"
        "404":
          description: "The given page does not exist or the provider name is not valid."
        "5XX":
          description: "Unexpected error."

  /images/v1/idx/list/image-names:
    get:
      summary: List all image names
      description: ""
      tags:
        - "V1 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_Image_Names_Response"
        "5XX":
          description: "Unexpected error."

  /images/v1/{provider}/{region}/{image-name}:
    get:
      summary: Get image details
      description: ""
      parameters:
      - in: path
        required: true
        name: provider
        schema:
          type: string
      - in: path
        required: true
        name: region
        schema:
          type: string
      - in: path
        required: true
        name: image-name
        schema:
          type: string
      tags:
        - "V1 Detailed Image Information"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V1_Image_Details_Response"
        "404":
          description: "The given provider,region or image-name does not exist."
        "5XX":
          description: "Unexpected error."

  /v2/os/list:
    get:
      summary: List all available operating systems
      description: ""
      tags:
        - "V2 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_OS_Response"
        "5XX":
          description: "Unexpected error."

  /v2/os/{os}/provider/list:
    get:
      summary: List all available products for the given os
      description: ""
      parameters:
        - in: path
          required: true
          name: os
          schema:
            type: string
      tags:
        - "V2 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_Provider_Response"
        "404":
          description: "The given page does not exist."
        "5XX":
          description: "Unexpected error."

  /v2/os/{os}/provider/{provider}/version/list:
    get:
      summary: List all available versions offered by this provider
      description: ""
      parameters:
      - in: path
        required: true
        name: os
        schema:
          type: string
      - in: path
        required: true
        name: provider
        schema:
          type: string
      tags:
        - "V2 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_Version_Response"
        "5XX":
          description: "Unexpected error."

  /v2/os/{os}/provider/{provider}/version/{version}/region/list:
    get:
      summary: List all regions for this specific version
      description: ""
      parameters:
      - in: path
        required: true
        name: os
        schema:
          type: string
      - in: path
        required: true
        name: provider
        schema:
          type: string
      - in: path
        required: true
        name: version
        schema:
          type: string
      tags:
        - "V2 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_Region_Response"
        "404":
          description: "The given page does not exist or the provider name is not valid."
        "5XX":
          description: "Unexpected error."

  /v2/os/{os}/provider/{provider}/version/{version}/region/{region}/image/list:
    get:
      summary: List all images for one specific region
      description: ""
      parameters:
      - in: path
        required: true
        name: os
        schema:
          type: string
      - in: path
        required: true
        name: provider
        schema:
          type: string
      - in: path
        required: true
        name: version
        schema:
          type: string
      - in: path
        required: true
        name: region
        schema:
          type: string
      tags:
        - "V2 List Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_Image_Response"
        "5XX":
          description: "Unexpected error."

  /v2/all:
    get:
      summary: Returns a list with all image details in one json file
      description: ""
      tags:
        - "V2 All Images"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/V2_All_Response"
        "404":
          description: "The given provider,region or image-name does not exist."
        "5XX":
          description: "Unexpected error."
